### ISSUE TITLE
Social options

### ISSUE THREAD

**Issue by dfm** [tess-science/online#10]
It would be nice to have some support for social components of the meeting beyond coffee breaks. These definitely shouldn't be mandatory or overly aggressively pushed since I expect a lot of folks will be pretty zoom-fatigued.

But, some things that we've talked about/were proposed in the applications:

1. A #social channel on Slack where people can self-organize. Remote board games? Animal crossing? Old fashioned happy hours?
2. A yotribe room that is always open where people can go to hang out if they need a break and are interested

**Comment by grd349** [comment]
+1 for happy hours.

Anyone for chess?  (How many board games cross multiple cultural boundaries?)

**Comment by benmontet** [comment]
I like the open yotribe room idea. 

I'm happy to lose to you at chess, Guy! I haven't played even remotely seriously since I was ~10.

It'd be good to aggregate a list of online things that would be good for larger groups. Have any of you used [tabletopia](https://tabletopia.com) before? I have not but I recognise some of the games and they have an 'easy to learn' section. There are also online trivia games.

**Comment by dfm** [comment]
We now have text in the Handbook about this and a Slack channel. I think we're good!
