### ISSUE TITLE
Draft facilitator handbook

### ISSUE THREAD

**Issue by dfm** [tess-science/online#4]
I'll update this with more info from Charley, but I think that what we want from facilitators is:

- To have someone available (perhaps in a list or a Slack channel or an email address?) to answer/help with technical and logistical questions (we will also probably normally have an organizer online too).
- To check in with participants to help make sure that folks are staying engaged. This will mostly be up to the project leads, but I think it's good to have backup here.
- It's also possible that we want these participants to also be available for handling issues within groups (interpersonal? structural? etc?) but perhaps that's too much to ask

**Comment by CharleyHaley** [comment]
Here are my initial thoughts:
1) Have a #help channel for participants to let you know they need help.
2) Have in the help channel a Zoom link or way to chat with someone directly, whoever is on duty at that time, if using Zoom make all facilitators co-host so that you can use one account.  Zoom will allow up to 50 co-hosts.  Or post a new link every x hours.
3) Maybe different links for different kinds of issues, e.g. For help about using slack & Zoom, about tutorials, project formation, team interactions, ... 
4) Some time in day 1, send out a short survey/form to participants where you can get a feel for how things are going, what needs adjusting, and ask anyone that would like direct support to add their name and contact info along with specifically what kind of help they want.   
5) As far as guidance to facilitators, I would hold 1 or 2 pre-event facilitator Zoom huddles to talk through what will be expected of everyone, have people signup in a spreadsheet whos online when, and see if anyone has any other ideas or sees any gaps in your strategy. If some facilitators want to specialize in a particular type of help have this spelled out somewhere so that if you are on duty you can redirect questions to the right person. 
6) During Coffee Breaks we could have one corner designate as a get help space where a facilitator stands and anyone wanting to chat about something can come over.  The background of the room can include this space.  

* if I have other ideas I'll add them.
