### ISSUE TITLE
Select participants and send informational email

### ISSUE THREAD

**Issue by dfm** [tess-science/online#5]
At this point we have just over 100 applications so hopefully we can accept most or all of these applications. I'd like to send some more information about the schedule and plan when sending acceptance so we might want to finish #3 first. Either way, I'd like to get this done before 27 Aug in NYC if at all possible.

**Comment by benmontet** [comment]
We are asking for quite a bit of legwork from participants before they start, so I believe strongly we should notify selected applicants asap!  The more time they have to read pitches, have conversations with other folks, figure out any new software tools we will ask them to use, the more likely they will have the bandwidth to carefully do these things. The faster we can turn these around to give them that time the better imo.

**Comment by dfm** [comment]
Totally agree! I think we probably need a few days to finish a draft of the handbook, but if we get it sooner, amazing! We could send an email before finishing the handbook with the "what to expect" section or something and then send a follow-up with the link when we're done?

**Comment by benmontet** [comment]
Yeah I think giving a what to expect, especially guidelines on what they’ll need to do before the conference is the most important thing. 

I’ll have time during the day Australia-tomorrow to put in words, feel free to task me with any specifics!

**Comment by dfm** [comment]
Will do - thanks! I'll be sprinting words today too if all goes as planned so I'll keep you posted!

**Comment by dfm** [comment]
I made no progress on drafting acceptance and rejection emails today so if @benmontet or @grd349 have time, that would be great. If not, no worries and I'll do them in the morning!

**Comment by benmontet** [comment]
Here's a draft acceptance email, feel free to modify as you see fit!

---

Dear all,

I am pleased to inform you that your application to online.tess.science has been selected. The meeting will begin at XXXX UTC on 8 September 2020, continuing for 48 hours.

To ensure the workshop gets off to a smooth start, there are a few tasks for all participants to do in advance. Please go through the following steps as soon as possible so that there is enough time for discussions before projects get started:

- First, read through the Participant Handbook so you know what to expect throughout the meeting. 

- Next, you should join the Slack workspace using THIS link and add your full name to your profile. While you're here, say hi to everyone in the #social channel!

- Add an introduction to the intros slide deck. These are approximately ordered by time zone, and should include your name, affiliation, research interests, expertise, and a description of what you want to work on and/or learn during online.tess.science. You can optionally include things like a photo of yourself, your pet, and/or other fun trivia about yourself. Please add your intro slide as soon as possible (don’t wait until the last minute!) so that everyone has a chance to “meet” you in advance.

- Finally, browse the project pitches on the pitches document and consider adding your own pitch (see the Project pitches section in the Handbook for more information). This document will be regularly updated by you and other participants, so check back from time to time before the start of the event. As you go through this list of project ideas, add your name to the “Interested participants” list for any that you are interested in and join the channel for that project on Slack. It’s worth having some discussions within each group about the scope and goals of the projects in order to hit the ground running when things get started.

Please don't hesitate to reach out if you have any questions! We're looking forward to seeing you soon.

Kind regards,

**Comment by dfm** [comment]
Amazing! I'll send this out shortly.

**Comment by dfm** [comment]
Done!
