### ISSUE TITLE
Set up infrastructure for code-of-conduct reports

### ISSUE THREAD

**Issue by dfm** [tess-science/online#7]
In the past we've had an anonymous form that the organizers have access to. Two issues:

1. It could be hard to report code of conduct violations related to the organizers
2. The organizational team is small this time and time zones might make it tricky to handle issues in a timely manner

One option: have a subset of facilitators (spanning the time zone range) who are responsible for code-of-conduct reports via:

- The online anonymous form, and
- Their contact info could be listed in the handbook so that participants could reach out to them directly if needed

**Comment by grd349** [comment]
2. I would be happy to be 'on call' outside of my time zone (perhaps not so much midnight to 06:00).  We could cover the time zone after our own time zone.  Happy to hand out my contact details for that.

**Comment by benmontet** [comment]
I can provide broad and anonymised statistics of how many people used the on-line anonymous form in the Chicago and Sydney meetings in a not-public setting of your choice. 

We've said at previous meetings that two specific SOC members were the point people for CoC issues, and I think the sensible extension of that is to have facilitators assigned to handle this that span time zones such that two of them are always online. (Two in case someone has an issue with a facilitator, they still feel like they can report it to someone). The anonymous google form on top of this is nice because we can set it up to buzz all of us immediately so any/all of us can handle it, and because of course sometimes folks want to be fully anonymous in reporting issues.

**Comment by dfm** [comment]
Do we think that the anonymous Slack workflows (#12) are sufficient for this or should we have another channel?

**Comment by benmontet** [comment]
The workflows provide Identical functionality of the previous google form, other than they go to four people rather than two. That seems ideal given the time zones. The only issue I see is people unwilling to use it if they have an issue with one of us, but given there’s only four of us that’s hard to navigate. Perhaps we have one or two of the facilitators who are also points of contact if there are issues, and we encourage people to use the workflow or reach out to them to handle it, and the facilitators will do their best to maintain any requisite privacy? Also open to alternative workarounds!

**Comment by dfm** [comment]
Good points! I think it's hard to satisfy all permutations so my proposal would be:

Use the "Facilitators" (optionally anonymous) workflow to report code of conduct issues. This will go to the organizers *and* all of the facilitators. Our default response will be to handle it as organizers, unless the issue is *with* an organizer. In which case, the currently logged in facilitators will be asked to take the lead.

It's a lot to ask of the facilitators, so we could alternatively ask for them to self-select if they are willing to handle code of conduct requests ("Super Facilitators"?) and just make sure that we always have a few logged in at all times?

**Comment by benmontet** [comment]
I think the default mode should be to the organisers, or a small sample of super-facilitators. It's harder to sell people that we will respect privacy if by default 15% of the attendees are immediately alerted about any issues, and that may limit people's willingness to notify on problems. We should limit the people 'in the loop' to the minimum number required to ensure 1-2 are always online in my opinion!

**Comment by dfm** [comment]
Good. I think that all makes sense and I've updated the text accordingly. Feel free to edit!

**Comment by dfm** [comment]
But I'm going to close this for now because I think we're set.
