### ISSUE TITLE
Design coffee break activities

### ISSUE THREAD

**Issue by dfm** [tess-science/online#9]
Coffee breaks will happen over Yotribe and we need to design a few activities and generally brainstorm how we want things to be structured.

**Comment by dfm** [comment]
e.g. What should be the background map be and what different sorts of areas do we want to specify?

**Comment by grd349** [comment]
I have always enjoyed randomly assigned breakouts.  Does Yotribe allow this or do you just make your own random walk?

**Comment by dfm** [comment]
I don't think there is support for exactly that, but there are a few ways that we can simulate it (as recommended by Charley).

1. We can have a "scavenger hunt" at some of the coffee breaks where you need to meet 1 person with each of some N characteristics (has a dog, codes in IDL, etc.)
2. We can provide a background image to yotribe (say, the Gaia image of the Galaxy) and then set places where people can go for specific purposes (e.g. go to the LMC to talk about asteroseismology and bicycles, and the Galactic Center to talk about de-trending methods and coffee-preparation-tips)

Charley is doing some prep for these sessions, but I think it would be good for us to have some suggestions to - there will be quite a few of these :D

**Comment by dfm** [comment]
Another thought: We could assign people a set of random numbers/letters/emojis and then everyone with the avocado emoji as their fourth character could gather in the Solar neighborhood with a particular prompt for discussion.

**Comment by dfm** [comment]
Also: I don't think that we need to structure *every* break like this. Maybe just every other one? It's nice to be able to just wander and chat too.

**Comment by benmontet** [comment]
In terms of how much content we need: A coffee break every 3 hours implies an attendee will encounter 2 or 3 of them each day, assuming 8 hour workdays.

It feels sensible to me to have Day 1 events be designed more as icebreaker style games with the goal of meeting new people, and once we've all met new people to have Day 2 be something different. 

It's probably true that every coffee break on Day 1 will be someone's first coffee break, and on day two everyone should in principle be experienced.

**Comment by dfm** [comment]
Good! I like this - icebreakers for all the coffee breaks on the first day (there will be 8, but it would definitely be fine to repeat activities) and then free form on the second!

**Comment by CharleyHaley** [comment]
Hi Everyone, 

Ok, I just finished designing 2 YoTribe Coffee Breaks for the Astro hackweek.  They wanted 30-minute coffee breaks so they are 30-min activities. As currently written up are designed to start on Zoom for the directions (because that is where their participants are) and then move onto YoTribe.  I realize that this will need to be changed for TESS's 48-hr hack. The directions for the Coffee breaks will need to be simplified and posted on Slack.  Once you are in YoTribe one of you, or I can do some of these, can talk/broadcast to everyone to facilitate more detailed directions in the beginning if necessary.  I have not thought about how well these will or will not translate to this self-organized event. They may need to be REALLy slimmed down. Basically look at this storyboard with 2 coffee braks as a place to start pushing back to say close, too far, etc.  The storyboard also has a couple of links to the possible backgrounds, but images are very personal.  Keep 'em or chuck 'em.  
 ~ Charley [https://docs.google.com/document/d/1ktXWBcZ8eOEoc5Yai4N4AzrJIir6XYi0NeYli4Q3YE0/edit?usp=sharing](url)

**Comment by CharleyHaley** [comment]
Oh, how long do you want your coffee breaks?

**Comment by dfm** [comment]
@CharleyHaley: Amazing - thanks for sharing! I'll take a closer look in the morning. I think we probably want to aim for more like 15 minutes of activity in the breaks. It's definitely fine if people take longer breaks, but in my experience people tend to be pretty excited to get back to hacking (at least in the face-to-face version).
